// generated by stringer -type=Panic; DO NOT EDIT

package validates

import "fmt"

const _Panic_name = "NON_POSITIVE_SIZE_PANICDIFFERENT_SIZE_PANICNOT_MULTIPLIABLE_PANICOUT_OF_RANGE_PANICINVALID_ELEMENTS_PANIC"

var _Panic_index = [...]uint8{0, 23, 43, 65, 83, 105}

func (i Panic) String() string {
	if i < 0 || i+1 >= Panic(len(_Panic_index)) {
		return fmt.Sprintf("Panic(%d)", i)
	}
	return _Panic_name[_Panic_index[i]:_Panic_index[i+1]]
}
